package org.wso2.brs.sample;
 
import org.wso2.brs.sample.LoanRequest;
import org.wso2.brs.sample.ResponseMessage;
 
rule "Loan Approval"
    when
        $request : LoanRequest(applicantSalary  >= 10000 && applicantAge >= 18);
    then
        System.out.println( "***********ACCEPT REQUEST*************" );
        ResponseMessage response = new ResponseMessage();
        response.setMessage("Loan Request ACCEPTED");
        insertLogical(response); 
end

rule "Loan Reject due to age less than 18 years"
    when
 	$request : LoanRequest(applicantAge   < 18);
    then
	System.out.println( "***********REJECT REQUEST due to age less than 18 years************" );
       	ResponseMessage response = new ResponseMessage();
       	response.setMessage("Loan Request REJECT due to age less than 18 years");
	insertLogical(response);
end

rule "Loan Reject due to salary less than 10000$"
    when
 	$request : LoanRequest(applicantSalary  < 10000);
    then
	System.out.println( "***********REJECT REQUEST due to salary less than 10000$************" );
       	ResponseMessage response = new ResponseMessage();
       	response.setMessage("Loan Request REJECT due to salary less than 10000$");
	insertLogical(response);
end
