package org.wso2.brs.sample;
 
import org.wso2.brs.sample.LoanRequest;
import org.wso2.brs.sample.ResponseMessage;
 
rule "Loan Approval"
    when
        $request : LoanRequest(applicantSalary  > 10000 && applicantAge >= 18);
    then
        System.out.println( "***********ACCEPT REQUEST*************" );
        ResponseMessage response = new RequestAccept();
        response.setMessage("Loan Request ACCEPTED");
        insertLogical(response); 
end

rule "Loan Reject"
    when
 	$request : LoanRequest(applicantAge   < 18);
    then
	System.out.println( "***********REJECT REQUEST*************" );
       	ResponseMessage response = new RequestAccept();
       	response.setMessage("Loan Request REJECT but age mismatch");
	insertLogical(response);
end
